#### 1

##### A Python library is a collection of functions and methods that allows users to perform various tasks without having to implement the functionality from scratch. We use Python libraries to save time and effort by leveraging pre-written code that provides solutions to common problems or tasks.


#### 2

##### The main differences between a NumPy array and a list are:

NumPy arrays are homogeneous collections of elements with a fixed size, whereas lists can contain elements of different data types and sizes.
NumPy arrays offer better performance for numerical operations compared to lists, especially for large datasets, due to optimized implementations of array operations.
NumPy arrays support vectorized operations, allowing mathematical operations to be applied element-wise, while lists require iteration for similar operations.


### 3

##### The shape, size, and dimension of the given array are:

Shape: (3, 4)
Size: 12 (total number of elements)
Dimension: 2 (2D array)


In [4]:
# 4
array = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
first_row = array[0]
print(first_row)


[1, 2, 3, 4]


In [5]:
# 5
array = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
element = array[2][3]
print(element)


12


In [7]:
# 6
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_elements = array[:, 1::2]
print(odd_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [8]:
# 7
import numpy as np

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.40938021 0.34997166 0.16175949]
 [0.44251888 0.31206623 0.46690007]
 [0.11019222 0.08596811 0.07337593]]


#### 8

##### np.random.rand generates random numbers from a uniform distribution between 0 and 1, while np.random.randn generates random numbers from a standard normal distribution (mean 0 and standard deviation 1).


In [9]:
# 9
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
expanded_array = np.expand_dims(array, axis=0)
print(expanded_array.shape)


(1, 3, 4)


In [10]:
#10
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transposed_array = np.transpose(array)
print(transposed_array)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [15]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Index-wise multiplication
index_wise_mul = A * B

# Matrix multiplication
matrix_mul = np.matmul(A, B)

# Add both matrices
matrix_addition = A + B

# Subtract matrix B from A
matrix_subtraction = A - B

# Divide matrix B by A
matrix_division = B / A

print("Index-wise multiplication:\n", index_wise_mul)
print("Matrix multiplication:\n", matrix_mul)
print("Matrix addition:\n", matrix_addition)
print("Matrix subtraction:\n", matrix_subtraction)
print("Matrix division:\n", matrix_division)


Index-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Matrix addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix division:
 [[9.         4.         2.33333333]
 [1.5        1.         0.66666667]
 [0.42857143 0.25       0.11111111]]


### 12

##### The function in NumPy used to swap the byte order of an array is np.ndarray.byteswap().


#### 13

##### The np.linalg.inv function is used to calculate the inverse of a square matrix. It is significant in linear algebra for solving systems of linear equations and other matrix operations.


In [14]:
# 14 
# reshaped_array = np.reshape(original_array, new_shape)



#### 15

##### Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes. NumPy automatically broadcasts arrays to make them compatible for element-wise operations, allowing you to perform operations between arrays of different shapes without explicitly adding dimensions.


In [ ]:
#### 1